version: '3'

services:
    db:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=testpass
            - MYSQL_DATABASE=chatapp
        volumes:
            - ./db/run:/var/lib/mysql
            - ./db/sql:/docker-entrypoint-initdb.d

    chatapp:
        build: .
        links:
            - db
        volumes:
            - .:/usr/src/app
        ports:
            - "18000:5000"
